{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.release_name }}-secret"
  labels:
    app: "{{ .Values.release_name }}"
type: Opaque
stringData:
  KEYSTORE_PASSWORD: {{ .Values.xtr.secrets.keystorePassword | quote }}
  KEY_PASS: {{ .Values.xtr.secrets.keyPass | quote }}
  VAULT_TOKEN: {{ .Values.xtr.secrets.vaultToken | quote }}
{{- end }}
