{{- if .Values.ingress.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.frontend.name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  labels:
    name: "{{ .Values.frontend.name }}-ingress"
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: "{{ .Values.frontend.name }}"
                port:
                  number: {{ .Values.frontend.service.port }}
  # tls:
  #   - hosts:
  #       - {{ .Values.domain }}
  #     secretName: {{ .Values.secretname }}
{{- end }}
