{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.backend.name }}-secret"
  labels:
    app: "{{ .Values.backend.name }}"
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URI: {{ .Values.backend.secrets.sqlalchemyDatabaseUri | quote }}
{{- end }}
