{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.release_name }}-secret"
  labels:
    app: "{{ .Values.release_name }}"
type: Opaque
stringData:
  VAULT_DEV_ROOT_TOKEN_ID: {{ .Values.vault.secrets.devRootTokenId | quote }}
{{- end }}
