replicas: 1
enabled: true

release_name: "vault"

# Vault Configuration
vault:
  image:
    repository: "hashicorp/vault"
    tag: "latest"
    pullPolicy: Always
  
  environment:
    serverPort: "8200"
    vaultAddr: "http://0.0.0.0:8200"

  # Sensitive values - stored in secret
  secrets:
    devRootTokenId: "root"

service:
  type: ClusterIP
  port: 8200

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "250m"
